//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comando.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class actions
    {
        public actions()
        {
            this.permissions = new HashSet<permissions>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string path { get; set; }
        public int moduleid { get; set; }
    
        public virtual ICollection<permissions> permissions { get; set; }
        public virtual modules modules { get; set; }
    }
}
