//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comando.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentByUsers
    {
        public int ID { get; set; }
        public int userid { get; set; }
        public int agentid { get; set; }
        public int levelid { get; set; }
    
        public virtual levels levels { get; set; }
        public virtual users users { get; set; }
        public virtual agents agents { get; set; }
    }
}
