//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comando.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<actions> actions { get; set; }
        public DbSet<AgentByUsers> AgentByUsers { get; set; }
        public DbSet<agents> agents { get; set; }
        public DbSet<components> components { get; set; }
        public DbSet<levels> levels { get; set; }
        public DbSet<modules> modules { get; set; }
        public DbSet<permissions> permissions { get; set; }
        public DbSet<profiles> profiles { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<users> users { get; set; }
    }
}
