//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comando.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.AgentByUsers = new HashSet<AgentByUsers>();
            this.profiles = new HashSet<profiles>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string usernamne { get; set; }
        public string password { get; set; }
        public int rolid { get; set; }
        public int configid { get; set; }
        public short isSA { get; set; }
        public short status { get; set; }
    
        public virtual ICollection<AgentByUsers> AgentByUsers { get; set; }
        public virtual ICollection<profiles> profiles { get; set; }
    }
}
